# Generated by Django 6.0.5 on 2026-06-27 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Mã vật tư')),
                ('name', models.CharField(max_length=100, verbose_name='Tên vật tư')),
                ('unit', models.CharField(max_length=20, verbose_name='Đơn vị tính')),
                ('quantity', models.IntegerField(default=0, verbose_name='Số lượng tồn')),
                ('min_quantity', models.IntegerField(default=5, verbose_name='Mức tồn tối thiểu')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Vị trí lưu kho')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('import', 'Nhập kho'), ('export', 'Xuất kho')], max_length=10, verbose_name='Loại giao dịch')),
                ('quantity', models.IntegerField(verbose_name='Số lượng thay đổi')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Ghi chú')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Ngày thực hiện')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.material', verbose_name='Vật tư')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người thực hiện')),
            ],
        ),
    ]
